language: node_js
node_js:
  - "0.12"

before_install:
  - npm -g install npm@latest-2
  - npm install -g gulp
  - npm install -g jspm
  - npm install
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm install

script: gulp
