language: node_js
node_js:
  - "0.12"

notifications:
  email:
    recipients:
      - $NOTIFICATION_EMAIL_RECIPIENT
    on_success: change
    on_failure: always

before_install:
  - npm -g install npm@latest-2
  - npm install -g gulp
  - npm install -g jspm
  - npm install
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm install

before_script:
  - pip install --user codecov

script: gulp

after_success:
  - cat coverage/*/lcov.info | codecov
